### ISSUE TITLE
Could not get this starter to work

### ISSUE THREAD

**Issue by zakkwylde** [zangster300/gonads-starter#1]
Also had an issue complaining about cookies and needing to delete them... even the first time I ran it... then that all it does.

https://github.com/zangster300/gonads-starter/blob/0efdb7795f8649524b36418e8f10354fe210e836/views/components/todo.templ#L28

Shows an issue with templ formatting. I did remove what thought was the issue but still did not work.

Could you review all the setup instructions again, please.

**Comment by zangster300** [comment]
Definitely going to add some better instructions imminently

Could you include what the formatting error was?

**Comment by zakkwylde** [comment]
[{
	"resource": "/Users/########/Development/GoProjects/gonads-starter/views/components/todo.templ",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "expected operand, found '{'",
	"source": "syntax",
	"startLineNumber": 28,
	"startColumn": 3,
	"endLineNumber": 28,
	"endColumn": 3
}]

**Comment by zangster300** [comment]
https://github.com/zangster300/gonads-starter/blob/main/README.md?plain=1#L58

Pretty sure this is what you are dealing with. If it continues let me know. Make sure this environment variable is set
